CREATE TABLE IF NOT EXISTS events(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  tags TEXT,
  all_day INTEGER NOT NULL,
  start DATETIME,
  end DATETIME,
  created_at DATETIME,
  updated_at DATETIME,
  version INTEGER NOT NULL
);